# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'annotatorpane.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets

class Ui_AnnotatorPane(object):
    def setupUi(self, AnnotatorPane):
        AnnotatorPane.setObjectName("AnnotatorPane")
        AnnotatorPane.resize(1241, 777)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AnnotatorPane.sizePolicy().hasHeightForWidth())
        AnnotatorPane.setSizePolicy(sizePolicy)
        AnnotatorPane.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.annotatorLayout = QtWidgets.QGridLayout(AnnotatorPane)
        self.annotatorLayout.setObjectName("annotatorLayout")
        self.graphicsView = GraphicsView(AnnotatorPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicsView.sizePolicy().hasHeightForWidth())
        self.graphicsView.setSizePolicy(sizePolicy)
        self.graphicsView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graphicsView.setObjectName("graphicsView")
        self.annotatorLayout.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.infoArea = QtWidgets.QWidget(AnnotatorPane)
        self.infoArea.setMinimumSize(QtCore.QSize(0, 100))
        self.infoArea.setObjectName("infoArea")
        self.infoGridLayout = QtWidgets.QGridLayout(self.infoArea)
        self.infoGridLayout.setHorizontalSpacing(6)
        self.infoGridLayout.setObjectName("infoGridLayout")
        self.labelProgress = QtWidgets.QLabel(self.infoArea)
        self.labelProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelProgress.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelProgress.setObjectName("labelProgress")
        self.infoGridLayout.addWidget(self.labelProgress, 0, 3, 1, 1)
        self.lineEditX1 = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditX1.setMinimumSize(QtCore.QSize(40, 21))
        self.lineEditX1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditX1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditX1.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditX1.setReadOnly(True)
        self.lineEditX1.setObjectName("lineEditX1")
        self.infoGridLayout.addWidget(self.lineEditX1, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.infoGridLayout.addItem(spacerItem, 0, 5, 1, 1)
        self.lineEditCurPos = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditCurPos.setMinimumSize(QtCore.QSize(120, 21))
        self.lineEditCurPos.setMaximumSize(QtCore.QSize(135, 16777215))
        self.lineEditCurPos.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditCurPos.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditCurPos.setReadOnly(True)
        self.lineEditCurPos.setObjectName("lineEditCurPos")
        self.infoGridLayout.addWidget(self.lineEditCurPos, 0, 1, 1, 1)
        self.labelX2 = QtWidgets.QLabel(self.infoArea)
        self.labelX2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelX2.setObjectName("labelX2")
        self.infoGridLayout.addWidget(self.labelX2, 2, 0, 1, 1)
        self.lineEditProgress = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditProgress.setMinimumSize(QtCore.QSize(80, 21))
        self.lineEditProgress.setMaximumSize(QtCore.QSize(80, 16777215))
        self.lineEditProgress.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditProgress.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lineEditProgress.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditProgress.setReadOnly(True)
        self.lineEditProgress.setObjectName("lineEditProgress")
        self.infoGridLayout.addWidget(self.lineEditProgress, 0, 4, 1, 1)
        self.lineEditY1 = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditY1.setMinimumSize(QtCore.QSize(40, 21))
        self.lineEditY1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditY1.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditY1.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditY1.setReadOnly(True)
        self.lineEditY1.setObjectName("lineEditY1")
        self.infoGridLayout.addWidget(self.lineEditY1, 1, 3, 1, 1)
        self.labelX1 = QtWidgets.QLabel(self.infoArea)
        self.labelX1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelX1.setObjectName("labelX1")
        self.infoGridLayout.addWidget(self.labelX1, 1, 0, 1, 1)
        self.labelCurPos = QtWidgets.QLabel(self.infoArea)
        self.labelCurPos.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelCurPos.setObjectName("labelCurPos")
        self.infoGridLayout.addWidget(self.labelCurPos, 0, 0, 1, 1)
        self.lineEditX2 = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditX2.setMinimumSize(QtCore.QSize(40, 21))
        self.lineEditX2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditX2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditX2.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditX2.setReadOnly(True)
        self.lineEditX2.setObjectName("lineEditX2")
        self.infoGridLayout.addWidget(self.lineEditX2, 2, 1, 1, 1)
        self.lineEditY2 = QtWidgets.QLineEdit(self.infoArea)
        self.lineEditY2.setMinimumSize(QtCore.QSize(40, 21))
        self.lineEditY2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEditY2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEditY2.setStyleSheet("font-family: \"Menlo\", \"Consolas\", monospace;")
        self.lineEditY2.setReadOnly(True)
        self.lineEditY2.setObjectName("lineEditY2")
        self.infoGridLayout.addWidget(self.lineEditY2, 2, 3, 1, 1)
        self.pushButtonZoomIn = QtWidgets.QPushButton(self.infoArea)
        self.pushButtonZoomIn.setMinimumSize(QtCore.QSize(32, 0))
        self.pushButtonZoomIn.setMaximumSize(QtCore.QSize(30, 32))
        self.pushButtonZoomIn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonZoomIn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonZoomIn.setStyleSheet("min-width: 30; font-family: \"Menlo\", \"Consolas\", monospace;")
        self.pushButtonZoomIn.setObjectName("pushButtonZoomIn")
        self.infoGridLayout.addWidget(self.pushButtonZoomIn, 0, 6, 1, 1)
        self.labelY1 = QtWidgets.QLabel(self.infoArea)
        self.labelY1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelY1.setObjectName("labelY1")
        self.infoGridLayout.addWidget(self.labelY1, 1, 2, 1, 1)
        self.labelY2 = QtWidgets.QLabel(self.infoArea)
        self.labelY2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelY2.setObjectName("labelY2")
        self.infoGridLayout.addWidget(self.labelY2, 2, 2, 1, 1)
        self.pushButtonZoomOut = QtWidgets.QPushButton(self.infoArea)
        self.pushButtonZoomOut.setMinimumSize(QtCore.QSize(32, 0))
        self.pushButtonZoomOut.setMaximumSize(QtCore.QSize(30, 32))
        self.pushButtonZoomOut.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonZoomOut.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonZoomOut.setStyleSheet("min-width: 30; font-family: \"Menlo\", \"Consolas\", monospace;")
        self.pushButtonZoomOut.setObjectName("pushButtonZoomOut")
        self.infoGridLayout.addWidget(self.pushButtonZoomOut, 0, 9, 1, 1)
        self.pushButtonOriginalSize = QtWidgets.QPushButton(self.infoArea)
        self.pushButtonOriginalSize.setMinimumSize(QtCore.QSize(32, 0))
        self.pushButtonOriginalSize.setMaximumSize(QtCore.QSize(30, 32))
        self.pushButtonOriginalSize.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonOriginalSize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonOriginalSize.setStyleSheet("min-width: 30; font-family: \"Menlo\", \"Consolas\", monospace;")
        self.pushButtonOriginalSize.setObjectName("pushButtonOriginalSize")
        self.infoGridLayout.addWidget(self.pushButtonOriginalSize, 0, 7, 1, 1)
        self.pushButtonFitInView = QtWidgets.QPushButton(self.infoArea)
        self.pushButtonFitInView.setMinimumSize(QtCore.QSize(32, 0))
        self.pushButtonFitInView.setMaximumSize(QtCore.QSize(30, 32))
        self.pushButtonFitInView.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonFitInView.setObjectName("pushButtonFitInView")
        self.infoGridLayout.addWidget(self.pushButtonFitInView, 1, 7, 1, 1)
        self.infoGridLayout.setColumnStretch(5, 1)
        self.annotatorLayout.addWidget(self.infoArea, 1, 0, 1, 1)
        self.labelButtonListWrapper = QtWidgets.QWidget(AnnotatorPane)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelButtonListWrapper.sizePolicy().hasHeightForWidth())
        self.labelButtonListWrapper.setSizePolicy(sizePolicy)
        self.labelButtonListWrapper.setMinimumSize(QtCore.QSize(90, 0))
        self.labelButtonListWrapper.setMaximumSize(QtCore.QSize(120, 16777215))
        self.labelButtonListWrapper.setBaseSize(QtCore.QSize(80, 0))
        self.labelButtonListWrapper.setObjectName("labelButtonListWrapper")
        self.vboxlayout = QtWidgets.QVBoxLayout(self.labelButtonListWrapper)
        self.vboxlayout.setObjectName("vboxlayout")
        self.pushButtonSkip = QtWidgets.QPushButton(self.labelButtonListWrapper)
        self.pushButtonSkip.setMinimumSize(QtCore.QSize(90, 0))
        self.pushButtonSkip.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButtonSkip.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonSkip.setObjectName("pushButtonSkip")
        self.vboxlayout.addWidget(self.pushButtonSkip)
        self.scrollAreaLabelButtons = QtWidgets.QScrollArea(self.labelButtonListWrapper)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaLabelButtons.sizePolicy().hasHeightForWidth())
        self.scrollAreaLabelButtons.setSizePolicy(sizePolicy)
        self.scrollAreaLabelButtons.setMinimumSize(QtCore.QSize(88, 0))
        self.scrollAreaLabelButtons.setMaximumSize(QtCore.QSize(120, 16777215))
        self.scrollAreaLabelButtons.setStyleSheet("QScrollArea { border: 1px dotted #999; }")
        self.scrollAreaLabelButtons.setWidgetResizable(True)
        self.scrollAreaLabelButtons.setObjectName("scrollAreaLabelButtons")
        self.labelButtonList = QtWidgets.QWidget()
        self.labelButtonList.setGeometry(QtCore.QRect(0, 0, 96, 696))
        self.labelButtonList.setMinimumSize(QtCore.QSize(84, 0))
        self.labelButtonList.setMaximumSize(QtCore.QSize(116, 16777215))
        self.labelButtonList.setObjectName("labelButtonList")
        self.labelButtonLayout = QtWidgets.QVBoxLayout(self.labelButtonList)
        self.labelButtonLayout.setContentsMargins(0, 12, 0, 0)
        self.labelButtonLayout.setObjectName("labelButtonLayout")
        self.scrollAreaLabelButtons.setWidget(self.labelButtonList)
        self.vboxlayout.addWidget(self.scrollAreaLabelButtons)
        self.annotatorLayout.addWidget(self.labelButtonListWrapper, 0, 1, 2, 1)
        self.tabWidget = QtWidgets.QTabWidget(AnnotatorPane)
        self.tabWidget.setObjectName("tabWidget")
        self.tabKey = QtWidgets.QWidget()
        self.tabKey.setObjectName("tabKey")
        self.label = QtWidgets.QLabel(self.tabKey)
        self.label.setGeometry(QtCore.QRect(40, 60, 121, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tabKey)
        self.label_2.setGeometry(QtCore.QRect(40, 120, 231, 41))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tabKey)
        self.label_3.setGeometry(QtCore.QRect(40, 180, 231, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tabKey)
        self.label_4.setGeometry(QtCore.QRect(40, 240, 231, 41))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.tabKey)
        self.label_5.setGeometry(QtCore.QRect(40, 300, 231, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.tabKey)
        self.label_6.setGeometry(QtCore.QRect(40, 360, 231, 41))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.tabKey)
        self.label_7.setGeometry(QtCore.QRect(40, 420, 231, 41))
        self.label_7.setObjectName("label_7")
        self.tabWidget.addTab(self.tabKey, "")
        self.tabResource = QtWidgets.QWidget()
        self.tabResource.setObjectName("tabResource")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabResource)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listViewImageNames = QtWidgets.QListView(self.tabResource)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewImageNames.sizePolicy().hasHeightForWidth())
        self.listViewImageNames.setSizePolicy(sizePolicy)
        self.listViewImageNames.setMinimumSize(QtCore.QSize(100, 0))
        self.listViewImageNames.setBaseSize(QtCore.QSize(80, 0))
        self.listViewImageNames.setFocusPolicy(QtCore.Qt.NoFocus)
        self.listViewImageNames.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.listViewImageNames.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listViewImageNames.setObjectName("listViewImageNames")
        self.verticalLayout.addWidget(self.listViewImageNames)
        self.tabWidget.addTab(self.tabResource, "")
        self.annotatorLayout.addWidget(self.tabWidget, 0, 2, 1, 1)
        self.controlButtonWrapper = QtWidgets.QWidget(AnnotatorPane)
        self.controlButtonWrapper.setMinimumSize(QtCore.QSize(0, 100))
        self.controlButtonWrapper.setObjectName("controlButtonWrapper")
        self.gridLayout = QtWidgets.QGridLayout(self.controlButtonWrapper)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonPrev = QtWidgets.QPushButton(self.controlButtonWrapper)
        self.pushButtonPrev.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonPrev.setObjectName("pushButtonPrev")
        self.gridLayout.addWidget(self.pushButtonPrev, 0, 0, 1, 1)
        self.pushButtonNext = QtWidgets.QPushButton(self.controlButtonWrapper)
        self.pushButtonNext.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonNext.setObjectName("pushButtonNext")
        self.gridLayout.addWidget(self.pushButtonNext, 0, 1, 1, 1)
        self.pushButtonDel = QtWidgets.QPushButton(self.controlButtonWrapper)
        self.pushButtonDel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonDel.setObjectName("pushButtonDel")
        self.gridLayout.addWidget(self.pushButtonDel, 1, 0, 1, 1)
        self.pushButtonSave = QtWidgets.QPushButton(self.controlButtonWrapper)
        self.pushButtonSave.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 2, 0, 1, 1)
        self.pushButtonExit = QtWidgets.QPushButton(self.controlButtonWrapper)
        self.pushButtonExit.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.gridLayout.addWidget(self.pushButtonExit, 2, 1, 1, 1)
        self.annotatorLayout.addWidget(self.controlButtonWrapper, 1, 2, 1, 1)
        self.annotatorLayout.setColumnStretch(0, 1)

        self.retranslateUi(AnnotatorPane)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(AnnotatorPane)

    def retranslateUi(self, AnnotatorPane):
        _translate = QtCore.QCoreApplication.translate
        AnnotatorPane.setWindowTitle(_translate("AnnotatorPane", "General Intelligence Image Annotator"))
        self.labelProgress.setText(_translate("AnnotatorPane", "Progress"))
        self.labelX2.setText(_translate("AnnotatorPane", "X2"))
        self.labelX1.setText(_translate("AnnotatorPane", "X1"))
        self.labelCurPos.setText(_translate("AnnotatorPane", "Cursor Position"))
        self.pushButtonZoomIn.setText(_translate("AnnotatorPane", "+"))
        self.labelY1.setText(_translate("AnnotatorPane", "Y1"))
        self.labelY2.setText(_translate("AnnotatorPane", "Y2"))
        self.pushButtonZoomOut.setText(_translate("AnnotatorPane", "-"))
        self.pushButtonOriginalSize.setText(_translate("AnnotatorPane", "1:1"))
        self.pushButtonFitInView.setText(_translate("AnnotatorPane", "Fit"))
        self.pushButtonSkip.setText(_translate("AnnotatorPane", "Skip"))
        self.label.setText(_translate("AnnotatorPane", "跳过当前图片：S键"))
        self.label_2.setText(_translate("AnnotatorPane", "载入上一张图片：P键或左方向键"))
        self.label_3.setText(_translate("AnnotatorPane", "载入下一张图片：N键或右方向键"))
        self.label_4.setText(_translate("AnnotatorPane", "图片放大：+键"))
        self.label_5.setText(_translate("AnnotatorPane", "图片缩小：-键"))
        self.label_6.setText(_translate("AnnotatorPane", "设置图片大小1:1 ：数字0键"))
        self.label_7.setText(_translate("AnnotatorPane", "显示支持图片格式：F7键"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabKey), _translate("AnnotatorPane", "快捷键"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabResource), _translate("AnnotatorPane", "项目资源"))
        self.pushButtonPrev.setText(_translate("AnnotatorPane", "Prev"))
        self.pushButtonNext.setText(_translate("AnnotatorPane", "Next"))
        self.pushButtonDel.setText(_translate("AnnotatorPane", "Delete"))
        self.pushButtonSave.setText(_translate("AnnotatorPane", "Save"))
        self.pushButtonExit.setText(_translate("AnnotatorPane", "Exit"))

from UI_instance.UI_Model.GraphicsView import GraphicsView
