# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_config(object):
    def setupUi(self, config):
        config.setObjectName("config")
        config.resize(1024, 768)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(config.sizePolicy().hasHeightForWidth())
        config.setSizePolicy(sizePolicy)
        config.setMinimumSize(QtCore.QSize(1000, 750))
        self.verticalLayout = QtWidgets.QVBoxLayout(config)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(5)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(config)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.btnAdd = QtWidgets.QPushButton(config)
        self.btnAdd.setObjectName("btnAdd")
        self.gridLayout.addWidget(self.btnAdd, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(config)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(config)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 1, 1, 1, 1)
        self.lblstatus = QtWidgets.QLabel(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblstatus.sizePolicy().hasHeightForWidth())
        self.lblstatus.setSizePolicy(sizePolicy)
        self.lblstatus.setWordWrap(True)
        self.lblstatus.setObjectName("lblstatus")
        self.gridLayout.addWidget(self.lblstatus, 1, 2, 1, 1)
        self.txtProjname = QtWidgets.QLineEdit(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtProjname.sizePolicy().hasHeightForWidth())
        self.txtProjname.setSizePolicy(sizePolicy)
        self.txtProjname.setMaximumSize(QtCore.QSize(16777215, 28))
        self.txtProjname.setObjectName("txtProjname")
        self.gridLayout.addWidget(self.txtProjname, 0, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 11)
        self.verticalLayout.addLayout(self.gridLayout)
        self.action_list = ActionList(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.action_list.sizePolicy().hasHeightForWidth())
        self.action_list.setSizePolicy(sizePolicy)
        self.action_list.setStyleSheet("QScrollArea { border: 1px dotted #999; }")
        self.action_list.setObjectName("action_list")
        self.verticalLayout.addWidget(self.action_list)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnLabelDel = QtWidgets.QPushButton(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelDel.sizePolicy().hasHeightForWidth())
        self.btnLabelDel.setSizePolicy(sizePolicy)
        self.btnLabelDel.setObjectName("btnLabelDel")
        self.horizontalLayout.addWidget(self.btnLabelDel)
        self.btnLabelAdd = QtWidgets.QPushButton(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnLabelAdd.sizePolicy().hasHeightForWidth())
        self.btnLabelAdd.setSizePolicy(sizePolicy)
        self.btnLabelAdd.setObjectName("btnLabelAdd")
        self.horizontalLayout.addWidget(self.btnLabelAdd)
        self.btnStart = QtWidgets.QPushButton(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStart.sizePolicy().hasHeightForWidth())
        self.btnStart.setSizePolicy(sizePolicy)
        self.btnStart.setObjectName("btnStart")
        self.horizontalLayout.addWidget(self.btnStart)
        self.returnBtn = QtWidgets.QPushButton(config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.returnBtn.sizePolicy().hasHeightForWidth())
        self.returnBtn.setSizePolicy(sizePolicy)
        self.returnBtn.setObjectName("returnBtn")
        self.horizontalLayout.addWidget(self.returnBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(config)
        QtCore.QMetaObject.connectSlotsByName(config)

    def retranslateUi(self, config):
        _translate = QtCore.QCoreApplication.translate
        config.setWindowTitle(_translate("config", "Form"))
        self.label.setText(_translate("config", "新建项目名称"))
        self.btnAdd.setText(_translate("config", "添加图片路径"))
        self.label_3.setText(_translate("config", "当前已选定图片路径"))
        self.lblstatus.setText(_translate("config", "当前状态：尚未选择图片"))
        self.btnLabelDel.setText(_translate("config", "删除标签"))
        self.btnLabelAdd.setText(_translate("config", "添加标签"))
        self.btnStart.setText(_translate("config", "开始标注"))
        self.returnBtn.setText(_translate("config", "返回主页"))

from UI_instance.UI_Model.ActionList import ActionList
